#pragma once

#include "effect.hpp"
#include "fx/biquad.hpp"
#include "fx/bitcrush.hpp"
#include "fx/chorus.hpp"
#include "fx/compressor.hpp"
#include "fx/compressor2.hpp"
#include "fx/delay.hpp"
#include "fx/distortion.hpp"
#include "fx/gain.hpp"
#include "fx/galactic.hpp"
#include "fx/reverb.hpp"
#include "fx/singlepole.hpp"
#include "fx/trancegate.hpp"
